---
abstract: 'Simple API to World Weather Online'
author:
  - 'Mateu Hunter C<hunter@missoula.org>'
  - 'Mateu X Hunter'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Weather-WWO
no_index:
  directory:
    - inc
    - t
requires:
  JSON: 0
  LWP::Simple: 0
  Moose: 1.21
  Regexp::Common: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
